table 'Base Países'
	lineageTag: 6f62b1d1-99e1-4f06-8f57-c2a99baa67a9

	column Nacionalidade
		dataType: string
		lineageTag: 3e5a5c95-7977-4416-b1ac-f007cefb25d9
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Nacionalidade

		annotation SummarizationSetBy = Automatic

	column Imagem
		dataType: string
		lineageTag: 6b02c053-5b2d-48f7-b498-c9c13eb0f466
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Imagem

		annotation SummarizationSetBy = Automatic

	partition 'Base Países' = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\Users\PPP Almoxarifado\Desktop\Projeto Dashboard Madrid\DataBase"),
				    #"C:\Users\PPP Almoxarifado\Desktop\Projeto Dashboard Madrid\DataBase\_Jogadores Madrid - Países Imagens csv" = Fonte{[#"Folder Path"="C:\Users\PPP Almoxarifado\Desktop\Projeto Dashboard Madrid\DataBase\",Name="Jogadores Madrid - Países Imagens.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"C:\Users\PPP Almoxarifado\Desktop\Projeto Dashboard Madrid\DataBase\_Jogadores Madrid - Países Imagens csv",[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"CSV Importado",{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Nacionalidade", type text}, {"Imagem", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

